### ISSUE TITLE
Where is parameter encoding?

### ISSUE THREAD

**Issue by ulysseyson** [HC-Guo/LogFormer#3]
https://github.com/HC-Guo/LogFormer/blob/630a77fbdb6432053c3cac0c65d941a7e4fab850/preprocess/preprocess_hdfs.py#L102C1-L117C35
Hi, I am interested in your paper Logformer, especially using Paramter Encoding to handle OOV and various parameters.
But I can't find the mechanism of it, your preprocessing looks like just drop paramters column.
Is it tended to not show public or just missed?

**Comment by HC-Guo** [comment]
Thank you for your attention on our work. This is base version of code without parameter encoding module, but it is still a very strong baseline for this task. Due to the company's interests, we do not plan to open source the final code version for now. Meanwhile, this portion of the code is sufficient for different purposes. Thank you again.

**Comment by ulysseyson** [comment]
That's okay. Thanks for answer the question!
